export enum Configuration {
    PORT = 'PORT',
    HOST_VPS = 'HOST_VPS',
    HOST_LOCAL = 'HOST_LOCAL',
    PORT_VPS_MONGO = 'PORT_VPS_MONGO',
    PORT_LOCAL_MONGO = 'PORT_LOCAL_MONGO',
    USR_DB_VPS = 'USR_DB_VPS',
    USR_DB_LOCAL = 'USR_DB_LOCAL',
    PWD_DB_VPS = 'PWD_DB_VPS',
    PWD_DB_LOCAL = 'PWD_DB_LOCAL',
    DATABASE_NAME = 'DATABASE_NAME',
}